# Customize this file, and then copy it to db.yaml
production:
    host:       'production_db_host'
    user:       'production_db_user'
    password:   'production_db_pass'
    name:       'production_db_name'
staging:
    host:       'staging_db_host'
    user:       'staging_db_user'
    password:   'staging_db_pass'
    name:       'staging_db_name'
